apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: teamflow-backend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5002
          env:
            - name: PORT
              value: "5002"
            - name: NODE_ENV
              value: "production"
            - name: MONGO_URI
              value: "mongodb://mongo-service:27017/teamflow"
            - name: JWT_SECRET
              value: "local-dev-secret-change-later"
